/**
 * questions.js
 * Las 128 afirmaciones del Perfil de Dones Espirituales.
 * Cada pregunta se asocia matemáticamente a un don mediante:
 *   giftIndex = (id - 1) % 16
 * (ver src/js/test-engine.js y docs/ARCHITECTURE.md)
 *
 * Módulo puro de datos: sin dependencias del DOM ni del navegador,
 * portable a cualquier entorno JS (Node, React Native, etc.).
 */

export const TOTAL_QUESTIONS = 128;
export const QUESTIONS_PER_PAGE = 8;
export const TOTAL_PAGES = TOTAL_QUESTIONS / QUESTIONS_PER_PAGE; // 16

export const questions = [
  { id: 1, text: 'Me inclino a motivar a otros para que participen.' },
  { id: 2, text: 'Me gusta empezar iglesias donde no hay creyentes.' },
  { id: 3, text: 'Puedo decir cuando la gente no es sincera.' },
  { id: 4, text: 'Me encanta oír sermones evangelísticos.' },
  { id: 5, text: 'La enseñanza sin aplicación práctica no está completa.' },
  { id: 6, text: 'Dios me ha dado pruebas extraordinarias de su control.' },
  { id: 7, text: 'La gente malentiende mis intereses financieros.' },
  { id: 8, text: 'Me encanta permitir que usen mi casa para reuniones.' },
  { id: 9, text: 'Mi estudio de la Biblia me da conocimiento especial.' },
  { id: 10, text: 'Prefiero ser EL líder, y no simplemente uno de los líderes.' },
  { id: 11, text: 'Tiendo a ser super sensible a las historias tristes.' },
  { id: 12, text: 'Tiendo a irritarme cuando la gente peca.' },
  { id: 13, text: 'Tiendo a sentirme frustrado cuando la iglesia no crece.' },
  { id: 14, text: 'Hago las cosas pequeñas que nadie más quiere hacer.' },
  { id: 15, text: 'Para mí la educación es muy importante.' },
  { id: 16, text: 'Tiendo a tomar decisiones y a hacer elecciones sabias.' },
  { id: 17, text: 'Puedo hacer muchas cosas a la vez.' },
  { id: 18, text: 'Estoy dispuesto a mudarme a otra parte para empezar una iglesia.' },
  { id: 19, text: 'Puedo decir cuando otros enseñan o dan información equivocada.' },
  { id: 20, text: 'Conducir a otros a Cristo es muy emocionante.' },
  { id: 21, text: 'Me gusta sugerir pasos prácticos de acción.' },
  { id: 22, text: 'Siempre creo y veo cómo Dios obra en nuestras vidas.' },
  { id: 23, text: 'Tiendo a dar dinero generosamente en donde más se necesita.' },
  { id: 24, text: 'Tiendo a hacer que personas totalmente extrañas se sientan como en casa.' },
  { id: 25, text: 'Tengo una capacidad especial para adquirir datos y principios bíblicos.' },
  { id: 26, text: 'Me siento frustrado cuando parece que nadie está a cargo.' },
  { id: 27, text: 'Paso mucho tiempo ayudando a otros a sentirse mejor.' },
  { id: 28, text: 'Discierno algo como malo antes que otros lo noten.' },
  { id: 29, text: 'Me encanta dirigir estudios bíblicos de discipulado.' },
  { id: 30, text: 'Prefiero servir a otros, en lugar de que me sirvan a mí.' },
  { id: 31, text: 'La preparación para hablar o enseñar es absolutamente necesaria.' },
  { id: 32, text: 'Parece que puedo ayudar a otros a tomar decisiones acertadas.' },
  { id: 33, text: 'Rindo mucho mejor cuando estoy bajo presión.' },
  { id: 34, text: 'Me adapto muy bien a otras culturas y grupos.' },
  { id: 35, text: 'Puedo diferenciar entre las necesidades reales y falsas.' },
  { id: 36, text: 'Me preocupan mucho las almas perdidas.' },
  { id: 37, text: 'Enseño lecciones bíblicas por tema, en lugar de versículo por versículo.' },
  { id: 38, text: 'Me resulta fácil confiar en Dios en lo imposible.' },
  { id: 39, text: 'Tiendo a hacer inversiones financieras sabias.' },
  { id: 40, text: 'Me gusta invitar a los necesitados para que se queden en mi casa.' },
  { id: 41, text: 'Aprendo y recuerdo fácilmente la verdad bíblica.' },
  { id: 42, text: 'Sé a dónde me dirijo y hago lo posible para que otros me acompañen.' },
  { id: 43, text: 'No puedo decir que "no" a necesidades legítimas.' },
  { id: 44, text: 'Investigo antes de hablar de la verdad, en lugar de simplemente estudiarla.' },
  { id: 45, text: 'Parece que encuentro lecciones espirituales en todo lo que ocurre.' },
  { id: 46, text: 'Resolver problemas es mi mayor preocupación.' },
  { id: 47, text: 'Me gusta explicar por qué algo es verdad.' },
  { id: 48, text: 'Fácilmente veo la diferencia entre la verdad y el error.' },
  { id: 49, text: 'Tiendo a hacerme cargo cuando nadie lo hace.' },
  { id: 50, text: 'Preferiría empezar una nueva iglesia, más que cualquier otra cosa.' },
  { id: 51, text: 'Puedo leer entre líneas en lo que otros dicen.' },
  { id: 52, text: 'La evangelización mundial realmente me entusiasma.' },
  { id: 53, text: 'Tiendo a usar ilustraciones bíblicas para explicar las cosas.' },
  { id: 54, text: 'Me siento cómodo con personas que oran mucho.' },
  { id: 55, text: 'La responsabilidad financiera es extremadamente importante.' },
  { id: 56, text: 'Busco oportunidades para usar mi casa para ayudar a otros.' },
  { id: 57, text: 'Estudio la Biblia para adquirir mayor conocimiento de las cosas.' },
  { id: 58, text: 'A menudo me ofrezco para hacerme cargo de proyectos difíciles.' },
  { id: 59, text: 'Algunos piensan que soy demasiado sensible.' },
  { id: 60, text: 'Me gusta proclamar la verdad que he recibido de Dios.' },
  { id: 61, text: 'A menudo procuro ayudar a las personas a crecer en Cristo.' },
  { id: 62, text: 'Tiendo a aprovechar muchas oportunidades para servir a las personas.' },
  { id: 63, text: 'Me molesta oír afirmaciones y enseñanzas incorrectas.' },
  { id: 64, text: 'La gente a menudo me busca para pedir consejo sabio.' },
  { id: 65, text: 'Me gustan los desafíos imposibles.' },
  { id: 66, text: 'Me emocionan mucho las nuevas obras misioneras en el mundo.' },
  { id: 67, text: 'Puedo detectar fácilmente las cosas que no son espirituales.' },
  { id: 68, text: 'Me encanta pedir a las personas que tomen una decisión por Cristo.' },
  { id: 69, text: 'Realmente me encanta animar a otros.' },
  { id: 70, text: 'Quiero que las personas oren más y aumenten su fe.' },
  { id: 71, text: 'Tiendo a discernir las verdaderas necesidades financieras.' },
  { id: 72, text: 'Mi casa siempre está abierta a cualquier persona o cualquier grupo.' },
  { id: 73, text: 'Tomo en serio el mandamiento de "crecer en el conocimiento."' },
  { id: 74, text: 'Me siento impulsado a avanzar incluso cuando otros no se sienten así.' },
  { id: 75, text: 'Cuando otros sufren, me siento obligado a ayudar.' },
  { id: 76, text: 'Puedo ser obstinado y difícil de convencer.' },
  { id: 77, text: 'Prefiero ser un líder espiritual.' },
  { id: 78, text: 'No me gusta estar al frente o dirigiendo algún grupo.' },
  { id: 79, text: 'Tiendo a preparar demasiado material.' },
  { id: 80, text: 'Me gusta resolver problemas mediante la sabiduría de la palabra de Dios.' },
  { id: 81, text: 'Me gusta organizar a las personas para realizar grandes tareas.' },
  { id: 82, text: 'Prefiero servir en un ministerio multi cultural.' },
  { id: 83, text: 'Soy buen juez de lo que es bueno y lo que es malo.' },
  { id: 84, text: 'Me gusta conducir a las personas a Cristo con mi testimonio.' },
  { id: 85, text: 'La aplicación práctica es de lo que se trata la enseñanza.' },
  { id: 86, text: 'Tengo firme seguridad de que Dios contesta la oración.' },
  { id: 87, text: 'Me gusta atender a tiempo las necesidades financieras.' },
  { id: 88, text: 'Una casa limpia y ordenada no es tan importante como una casa disponible.' },
  { id: 89, text: 'A menudo me siento obligado a estudiar y aprender la verdad bíblica.' },
  { id: 90, text: 'La gente a menudo dice que soy un buen líder.' },
  { id: 91, text: 'Trato de presentarme como cariñoso e interesado.' },
  { id: 92, text: 'Tiendo a saber por qué la gente hace lo que hace.' },
  { id: 93, text: 'Me atrae mucho guiar a grupos a la madurez espiritual.' },
  { id: 94, text: 'Tiendo a hacer mucho más de lo que se me ordena.' },
  { id: 95, text: 'Estudiar las Escrituras es mi pasión.' },
  { id: 96, text: 'Creo que la sabiduría es más importante que la fe o el conocimiento.' },
  { id: 97, text: 'Prefiero decir lo que pienso, en lugar de dejar que las cosas simplemente pasen.' },
  { id: 98, text: 'Me atraen los ministerios que empiezan nuevas iglesias.' },
  { id: 99, text: 'La gente dice que a menudo doy el consejo preciso.' },
  { id: 100, text: 'Puedo hablarles del evangelio a personas totalmente extrañas.' },
  { id: 101, text: 'A menudo me siento obligado a dar consejos.' },
  { id: 102, text: 'Tiendo a juzgar a las personas por el grado de fe que tienen.' },
  { id: 103, text: 'Me preocupa atender las necesidades financieras y físicas.' },
  { id: 104, text: 'Siento que los miembros de la iglesia necesitan ser más hospitalarios.' },
  { id: 105, text: 'Me gusta aprender cosas que la mayoría de la gente no sabe.' },
  { id: 106, text: 'Me molesta cuando la gente se queda sentada sin hacer nada.' },
  { id: 107, text: 'Tiendo a ofrecerme como voluntario para ayudar a los menos afortunados.' },
  { id: 108, text: 'Confrontar a alguien con el pecado que hay en su vida no es difícil.' },
  { id: 109, text: 'La gente me busca para ser más fuertes espiritualmente.' },
  { id: 110, text: 'Trabajar tras bambalinas me da mucho placer.' },
  { id: 111, text: 'Yo busco nueva revelación mientras estudio.' },
  { id: 112, text: 'La gente a menudo se asombra por el mucho conocimiento que tengo.' },
  { id: 113, text: 'Delego las responsabilidades a fin de realizar las tareas.' },
  { id: 114, text: 'Creo que un apóstol es hoy el pionero y autoridad de Dios.' },
  { id: 115, text: 'Parece que tengo discernimiento singular en muchos aspectos.' },
  { id: 116, text: 'Proclamar mi fe es lo más importante para mí.' },
  { id: 117, text: 'Realmente disfruto al aconsejar a otros.' },
  { id: 118, text: 'La gente dice que tengo una gran cantidad de fe.' },
  { id: 119, text: 'Ser holgazán y ocioso en los negocios es un pecado.' },
  { id: 120, text: 'Creo que la hospitalidad es una de las cosas más importantes.' },
  { id: 121, text: 'Creo que tener gran conocimiento es muy importante.' },
  { id: 122, text: 'La oposición no me fastidia tanto como quedarme sin hacer nada.' },
  { id: 123, text: 'Me preocupa mucho cómo se siente una persona.' },
  { id: 124, text: 'La gente dice que soy demasiado protector y estricto con otros.' },
  { id: 125, text: 'Me gusta ayudar a otros a participar en el ministerio.' },
  { id: 126, text: 'Prefiero hacer una tarea yo mismo antes que delegarla.' },
  { id: 127, text: 'Hurgar hondo en la palabra de Dios es una prioridad en mi vida.' },
  { id: 128, text: 'La gente a menudo dice que demuestro mucha sabiduría extraordinaria.' },
];
